# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      # Ruff - 自动格式化
      - id: ruff-format
        name: ruff format
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run ruff format "$@"' --
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true
      
      # Ruff - 自动修复问题
      - id: ruff-check
        name: ruff check and fix
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run ruff check --fix "$@"' --
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true